apiVersion: v1
kind: Service
metadata:
  name: generatordemisie-service
spec:
  selector:
    app: generatordemisie
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: generatordemisie-deployment
  annotations:
    author: Vlad Moisuc
  labels:
    app: generatordemisie
    environment: dev
    tier: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: generatordemisie
  template:
    metadata:
      labels:
        app: generatordemisie
    spec:
      containers:
        - name: generatordemisie
          image: vladmoisuc/generatordemisie:1.0
          ports:
            - containerPort: 3000
